version: "3.9"

networks:
  shared-network:

services:
  web:
    image: nginx
    container_name: web
    ports:
      - 80:80
    networks:
      - shared-network
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - user-module

  user-module:
    image: local-user-module
    container_name: user-module
    build: 
      context: modules/user
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongod:27017/testdb?authSource=admin
    networks:
      - shared-network
    volumes:
      - ./resto:/usr/local/lib/python3.9/site-packages/resto
      - ./modules/user/app/resto/controllers/user.py:/usr/local/lib/python3.9/site-packages/resto/controllers/user.py
      - ./modules/user/app/resto/models/user.py:/usr/local/lib/python3.9/site-packages/resto/models/user.py
    ports:
      - 8080:5000
    depends_on:
      - mongod

  mongod:
    image: mongo:latest
    container_name: mongod
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - shared-network
    volumes:
      - mongod_data:/data/db

volumes:
  mongod_data:
    

